version: '3'

tasks:
  #### Default ####
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  #### Utility ####
  setup:
    desc: Run all setup tasks
    cmds:
      - task setup:mod
      - task setup:lint
      - task setup:test
    silent: true

  setup:mod:
    desc: Download and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
    silent: true

  setup:lint:
    desc: Install necessary linting tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    silent: true

  setup:test:
    desc: Install necessary testing tools
    cmds:
      - go install gotest.tools/gotestsum@latest
      - go install github.com/axw/gocov/gocov@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
    silent: true

  #### Lint ####
  lint:
    desc: Run golangci-lint
    cmd: golangci-lint run ./...
    silent: true

  #### Test ####
  test:
    desc: Run all tests for all packages
    cmd: gotestsum --format testname --format-hide-empty-pkg ./...
    silent: true

  coverage:
    desc: Generate coverage information for all packages
    cmd: gocov test ./... | gocov report
    silent: true
